<?php

return [
    'Allemagne' => 'Allemagne',
    'Belgique' => 'Belgique',
    'Bénin' => 'Bénin',
    'Burkina Faso' => 'Burkina Faso',
    'Burundi' => 'Burundi',
    'Cameroun' => 'Cameroun',
    'Cap-Vert' => 'Cap-Vert',
    'République Centrafricaine' => 'République Centrafricaine',
    'Comores' => 'Comores',
    'Congo' => 'Congo',
    'République Démocratique du Congo' => 'République Démocratique du Congo',
    'Côte d\'Ivoire' => 'Côte d\'Ivoire',
    'Djibouti' => 'Djibouti',
    'Égypte' => 'Égypte',
    'Espagne' => 'Espagne',
    'France' => 'France',
    'Gabon' => 'Gabon',
    'Royaume-Uni' => 'Royaume-Uni',
    'Guinée' => 'Guinée',
    'Guinée-Bissau' => 'Guinée-Bissau',
    'Haïti' => 'Haïti',
    'Italie' => 'Italie',
    'Liban' => 'Liban',
    'Liberia' => 'Liberia',
    'Libye' => 'Libye',
    'Luxembourg' => 'Luxembourg',
    'Madagascar' => 'Madagascar',
    'Mali' => 'Mali',
    'Maroc' => 'Maroc',
    'Maurice' => 'Maurice',
    'Mauritanie' => 'Mauritanie',
    'Monaco' => 'Monaco',
    'Niger' => 'Niger',
    'Portugal' => 'Portugal',
    'Rwanda' => 'Rwanda',
    'Sénégal' => 'Sénégal',
    'Seychelles' => 'Seychelles',
    'Suisse' => 'Suisse',
    'Tchad' => 'Tchad',
    'Togo' => 'Togo',
    'Tunisie' => 'Tunisie',
    'Vanuatu' => 'Vanuatu',
];